enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: false

preferAggregateCacheInfo: true

preferInteractive: true

<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-3.1.1.cjs
=======
yarnPath: .yarn/releases/yarn-3.3.1.cjs
>>>>>>> 0211ff308517c3a4c9c8c135f9c218015cfecbb7
