name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build and Publish Docker Image to Registry
<<<<<<< HEAD
        uses: elgohr/Publish-Docker-Github-Action@master
=======
        uses: elgohr/Publish-Docker-Github-Action@v5
>>>>>>> 0211ff308517c3a4c9c8c135f9c218015cfecbb7
        with:
          name: tgstation/tgstation
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest"
